---
- name: Ensure system is unregistered with RHC
  hosts: sat_systems
  tags: [teardown, never]
  become: true 

  vars:
    target: sat_systems
    rhc_auth:
      login:
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
    rhc_state: absent 
    rhc_insights:
      state: absent

  roles:
    - redhat.rhel_system_roles.rhc


- name: Shutdown and remove existing virtual machines 
  hosts: kvm_host
  tags: [teardown, never]
  gather_facts: false
  become: true 

  tasks: 
    - name: Stop all node VMs
      community.libvirt.virt:
        name: "{{ item.key }}"
        state: shutdown
      loop: "{{ satellite_systems | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      failed_when: false # doesn't really matter, we are deleting them anyway

    - name: Pause for vms to shutdown 
      ansible.builtin.pause:
        seconds: 10 

    - name: Undefine node VMs
      community.libvirt.virt:
        command: undefine
        name: "{{ item.key }}"
        # force: true
      loop: "{{ satellite_systems | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      failed_when: false 

    - name: Pause for vms to undefine 
      ansible.builtin.pause:
        seconds: 15
