---
- name: Satellite installation
  hosts: satellite
  tags: [sat_install]
  become: true 

  tasks:
    - name: Register and prep repos for Satellite install 
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.rhc
      vars:
        rhc_state: present 
        rhc_auth:
          login:
            username: "{{ rh_username }}"
            password: "{{ rh_password }}"
        rhc_repositories:
          - { name: "rhel-9-for-x86_64-baseos-rpms", state: enabled }
          - { name: "rhel-9-for-x86_64-appstream-rpms", state: enabled }
          - { name: "codeready-builder-for-rhel-9-x86_64-rpms", state: disabled }
          - { name: "satellite-6.16-for-rhel-9-x86_64-rpms", state: enabled }
          - { name: "satellite-maintenance-6.16-for-rhel-9-x86_64-rpms", state: enabled }

    - name: Run Satellite installer 
      ansible.builtin.include_role:
        name: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_package: satellite-installer
        satellite_installer_options:
          - '--foreman-initial-organization "{{ sat_org_name }}"'
          - '--foreman-initial-admin-username {{ sat_admin_username }}'
          - '--foreman-initial-admin-password {{ sat_admin_password }}'
          - '--foreman-initial-location "{{ sat_location }}"'

    - name: permanently enable RH-Satellite-6 service 
      ansible.posix.firewalld:
        service: RH-Satellite-6
        state: enabled
        permanent: true
        immediate: true
        offline: true
