---
- name: Setup Satellite OpenSCAP for demo
  hosts: satellite
  tags: [scap_configure]
  become: true 

  vars: 
    default_scap_content:
      - title: Red Hat rhel10 default content
        scap_file: /usr/share/xml/scap/ssg/content/satellite/ssg-rhel10-ds.xml
      - title: Red Hat rhel6 default content
        scap_file: /usr/share/xml/scap/ssg/content/satellite/ssg-rhel6-ds.xml
      - title: Red Hat rhel7 default content
        scap_file: /usr/share/xml/scap/ssg/content/satellite/ssg-rhel7-ds.xml
      - title: Red Hat rhel8 default content
        scap_file: /usr/share/xml/scap/ssg/content/satellite/ssg-rhel8-ds.xml
      - title: Red Hat rhel9 default content
        scap_file: /usr/share/xml/scap/ssg/content/satellite/ssg-rhel9-ds.xml

  tasks:
    - name: Create SCAP content
      redhat.satellite.scap_content:
        title: "{{ item.title }}"
        scap_file: "{{ item.scap_file }}"
        organizations:
          - "{{ sat_org_name }}"
        locations:
          - "{{ sat_location }}"
        server_url: "{{ sat_server_url }}"
        validate_certs: false
        username: "{{ sat_admin_username }}"
        password: "{{ sat_admin_password }}"
        state: present
      loop: "{{ default_scap_content }}"

    - name: Create foreman hammer auth file
      ansible.builtin.blockinfile:
        path: "~/.hammer/cli.modules.d/foreman.yml"
        block: |
          :foreman:
           :username: {{ sat_admin_username }}
           :password: {{ sat_admin_password }}

    - name: Look up profile ids 
      # this extra step is needed b/c the hammer command to create policies fails if you try to add policy by name
      ansible.builtin.shell: |
          set -o pipefail
          hammer scap-content-profile list \ 
          --search "title=\"PCI-DSS v4.0.1 Control Baseline for Red Hat Enterprise Linux {{ item }}\"" \ 
          --fields id \ 
          | awk '{printf "%s", $2}'
      args:
        executable: /bin/bash
      loop:
        - 8
        - 9
        - 10
      register: profile
      changed_when: false

    - name: Create SCAP policies
      ansible.builtin.shell: |  
          hammer policy create \
          --deploy-by "manual" \
          --name "PCI_Compliance_{{ item.item }}" \ 
          --description "OpenSCAP PCI Compliance Policy - RHEL {{ item.item }}" \ 
          --scap-content "Red Hat rhel{{ item.item }} default content" \ 
          --scap-content-profile-id {{ item.stdout }} \ 
          --period "monthly" \ 
          --day-of-month 1
      args:
        executable: /bin/bash
      loop: "{{ profile.results }}"
      loop_control:
        label: "{{ item.item }}"
      register: output
      changed_when: '"Policy created" in output.stdout'
      failed_when:
        - output.rc != 0
        - '"Name has already been taken" not in output.stderr'

    - name: Refresh dynamic inventory
      ansible.builtin.meta:
        refresh_inventory
