---
- name: Provision a KVM Virtual Machine using virt_install module
  hosts: kvm_host
  become: true
  vars:
    # Images
    rhel8_0image: "/var/lib/libvirt/images/rhel-8.0-x86_64-kvm.qcow2"
    rhel8_10image: "/var/lib/libvirt/images/rhel-8.10-x86_64-kvm.qcow2"
    rhel9_7image: "/var/lib/libvirt/images/rhel-9.7-x86_64-kvm.qcow2"
    rhel10_1image: "/var/lib/libvirt/images/rhel-10.1-x86_64-kvm.qcow2"

    # values common to all vms
    common:
      deploy_vm_base_domain: "eversmann.xyz"
      deploy_vm_vcpus: 2
      deploy_vm_memory_mb: 4096
      deploy_vm_disk_path: "/var/lib/libvirt/images/"
      deploy_vm_users:
        - username: damien
          fullname: Damien Eversmann
          ssh_public_key: "{{ lookup('file', 'files/id_rsa.pub') }}"
          is_admin: true

    # list of values specific to each vm
    vm_specifics:
      - deploy_vm_name: "rhel-server-8_0"
        deploy_vm_base_image: "{{ rhel8_0image }}"
        deploy_vm_osinfo: "rhel8-unknown"
      - deploy_vm_name: "rhel-server-8_10"
        deploy_vm_base_image: "{{ rhel8_10image }}"
        deploy_vm_osinfo: "rhel8-unknown"
      - deploy_vm_name: "rhel-server-9_7"
        deploy_vm_base_image: "{{ rhel9_7image }}"
        deploy_vm_osinfo: "rhel9-unknown"
      - deploy_vm_name: "rhel-server-10_1"
        deploy_vm_base_image: "{{ rhel10_1image }}"
        deploy_vm_osinfo: "rhel10-unknown"

    # merged vm definitions
    vm_definitions: "{{ vm_specifics | map('combine',common,list_merge='keep') }}"

  tasks:
    - name: Include deploy_vm role
      ansible.builtin.include_role:
        name: deploy_vm
      loop: "{{ vm_definitions }}"
      loop_control:
        loop_var: deploy_vm_definition

...
