--- 
- name: Register with rhc 
  hosts: "{{ target | default('localhost') }}"
  become: true 

  vars:
    rhc_state: present
    rhc_auth:
      login:
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
    rhc_repositories:
      - {name: "rhel-10-for-x86_64-baseos-rpms", state: enabled}
      - {name: "rhel-10-for-x86_64-appstream-rpms", state: enabled}
      - {name: "codeready-builder-for-rhel-10-x86_64-rpms", state: enabled}
    rhc_insights:
      state: present
      autoupdate: false
      remediation: false

  roles:
    - redhat.rhel_system_roles.rhc
