--- 
# - name: Register with satellite  
#   hosts: sat_clients # "{{ target | default('localhost') }}"
#   become: yes 

#   vars:
#     rhc_state: present
#     rhc_server:
#       hostname: sat01.aj.peripatetic.us
#       prefix: /rhsm
#       insecure: true
#     rhc_auth:
#       activation_keys:
#         keys:  
#           - Clients
#     rhc_organization: "Jerry_s_Chop_Shop"
#     rhc_baseurl: "https://sat01.aj.peripatetic.us/pulp/content"
#     rhc_insights:
#       state: present
#       autoupdate: false
#       remediation: false

#   roles:
#     - redhat.rhel_system_roles.rhc

- name: Register with insights
  hosts: sat_clients # "{{ target | default('localhost') }}"
  become: yes 

  vars:
    rhc_state: reconnect 
    rhc_server:
      hostname: console.redhat.com
      prefix: /rhsm
      insecure: true
    # rhc_auth:
    #   activation_keys:
    #     keys:  
    #       - homelab
    rhc_organization: "12762124"
    rhc_auth:
      login:
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
    rhc_insights:
      state: present
      autoupdate: false
      remediation: absent
      ansible_host: "{{ inventory_hostname }}"
  roles:
    - redhat.rhel_system_roles.rhc