--- 
- name: Register with satellite  
  hosts: sat_clients # "{{ target | default('localhost') }}"
  become: true 
  serial: 1 

  vars:
    satellite_server_url: "https://{{ sat_hostname }}"
    # role vars
    rhc_state: present
    rhc_server:
      hostname: "{{ sat_hostname }}"
      prefix: /rhsm
      insecure: true
    rhc_auth:
      activation_keys:
        keys:  
          - "RHEL{{ ansible_distribution_major_version }}Clients"
    rhc_organization: "{{ sat_org_name }}"
    rhc_baseurl: "https://{{ sat_hostname }}/pulp/content"
    rhc_insights:
      state: present
      autoupdate: true
      remediation: present

  # roles:
  #   - redhat.rhel_system_roles.rhc

  tasks:
    - name: "Generate registration command"
      redhat.satellite.registration_command:
        organization: "{{ sat_org_name }}"
        activation_keys: 
          - "RHEL{{ ansible_distribution_major_version }}Clients"
        username: "admin"
        password: "{{ sat_admin_password }}"
        server_url: "{{ satellite_server_url }}"
        lifecycle_environment: "Dev"
        setup_insights: true 
        insecure: true 
        validate_certs: false 
        force: true 
      register: command
      delegate_to: localhost

    - name: "Perform registration"
      ansible.builtin.shell:
        cmd: "{{ command.registration_command }}"

    # - name: Trigger immediate upload of Lightspeed (Insights) inventory data
    #   ansible.builtin.command:
    #     cmd: "foreman-rake rh_cloud_inventory:report:generate_upload organization_id=1"
    #   register: output
    #   failed_when: "output.rc != 0 or 'Generated and uploaded inventory report' not in output.stdout"
    #   changed_when: "'Generated and uploaded inventory report' in output.stdout"
